version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BACKEND=http://localhost:3000
    ports:
      - 80:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.output
      - /app/.nuxt

